### ISSUE TITLE
estimate gas(transaction) fee before sending transaction?

### ISSUE THREAD

**Issue by Davidzsy20** [iamnotstatic/multichain-crypto-wallet#14]

**Comment by iamnotstatic** [comment]
Hi @Davidzsy20.. Can you give more context on the issue

**Comment by fly33499** [comment]
> Hi @Davidzsy20.. Can you give more context on the issue

As my understanding, you can see below link to set transaction fee as option.
Probably, Davidzsy20 want to set these value. Because, BTC tx fees change up to down frequently.

https://github.com/renproject/send-crypto/blob/master/src/handlers/BTC/BTCHandler.ts


Thank you for great library.

**Comment by Davidzsy20** [comment]
> > Hi @Davidzsy20.. Can you give more context on the issue
> 
> As my understanding, you can see below link to set transaction fee as option. Probably, Davidzsy20 want to set these value. Because, BTC tx fees change up to down frequently.
> 
> https://github.com/renproject/send-crypto/blob/master/src/handlers/BTC/BTCHandler.ts
> 
> And, you can see fee variation below link. (recommend fee is 0.0003 BTC) https://bitonic.nl/en/faq/29/im-sending-bitcoins-what-is-the-miners-fee
> 
> Thank you for great library.

thank you for the explanation.

**Comment by Davidzsy20** [comment]
> Hi @Davidzsy20.. Can you give more context on the issue?

So, before sending a transaction, the user needs to estimate gas for the proposed transaction, usually in form of a regular/priority fee, and add it to the base amount to calculate the total amount for a transaction.
