### ISSUE TITLE
How to support more chains

### ISSUE THREAD

**Issue by frodoe7** [iamnotstatic/multichain-crypto-wallet#16]
I see the library support 3 chains (Bitcoin/Solana/Ethereum)

What if I'd like to support Binance Smart Chain (BSC)?

**Comment by iamnotstatic** [comment]
Hi, the way the library is designed it supports all EVM compatible chains all you have to do is pass the chain RPC URL.. 
For instance, if I want to get a balance on Binance smart chain mainnet this what you need to do.

```js
const data = await multichainWallet.getBalance({
  address: '0x2455eC6700092991Ce0782365A89d5Cd89c8Fa22',
  network: 'ethereum',
  rpcUrl: 'https://bsc-dataseed.binance.org/',
});
```

**Comment by frodoe7** [comment]
I recommend to explain that in the docs, as every example for (Bitcoin/Solana/Ethereum)
Anyway, thanks so much
