### ISSUE TITLE
solana not showing exact balance

### ISSUE THREAD

**Issue by nihal-01** [iamnotstatic/multichain-crypto-wallet#17]
#### Steps to reproduce the behavior

1. [First step]
2. [Second step]
3. [and so on...]

**Comment by iamnotstatic** [comment]
Hi @nihal-01 , Can you elaborate on the issue, Did you experience this on the Solana testnet or the mainnet ?

**Comment by nihal-01** [comment]
in my solana test net i have only 1 sol. but it showing 1000000000 SOL

rpc url = https://api.testnet.solana.com

this same issue on https://api.devent.solana.com
