### ISSUE TITLE
How can I do this with the repo?

### ISSUE THREAD

**Issue by zydjohnHotmail** [iamnotstatic/multichain-crypto-wallet#18]
#### Steps to reproduce the behavior

1. [First step]
2. [Second step]
3. [and so on...]

#### Logs
Just ask some general questions before going one step further.

#### Environment
Node.js (Version 19.1.0)
OS: Windows 10 Pro (Version 22H2)

Hello:
I found your repo, it seems to be a good one.  I want to know if I can do the following with this repo?
I want to create a mult-chain wallet with one address for multiple networks: ERC20, BEP20, Solana and Bitcoin.
Then with the wallet, I want to be able to receive some funds from my wallet in Binance using BEP20, then after I get the funds, I want to be able to send the funds to my wallet in Huobi using ERC20, since in Huobi, some funds have only addresses in ERC20.
And in Binance, many currencies have only BEP20 addresses.
And yet, with the same address or another one in my wallet, I want to send some funds to another wallet in another exchange using Solana or using Bitcoin address.
I think the same address can be used for both ERC20 and BEP20, right?
But the SOLANA address format looks different from those address format in ERC20 and BEP20, also Bitcoin address format also very different from other network addresses.
So, in order to do what I want with this repo, how many addresses I have to create?
I think I need 3 different addresses for 4 different networks, right?
Let me know if I am wrong.
By the way, to create any address, do I have to use those 12-words paraphrase?
Finally, if I can receive the funds in my multi-chain wallet, how can I calculate the gas fees before I send some funds to other exchange’s wallet address?
Most exchanges have some kind of fees table for withdraw, just like here for sending funds to another wallet address, can I find such information before sending the funds to my wallet in other exchanges?
I have some experience with Node.JS (version 19.1.0), but I am not an expert.
Please advise,
Thanks,

**Comment by iamnotstatic** [comment]
> 

Hi @zydjohnHotmail, To achieve this you need to create just 3 addresses which are Ethereum, Solana, and Bitcoin for the Ethereum address you can use it to receive funds from any EVM-compatible chains, like Binance Smart Chain, Polygon, etc.

Also In terms of the gas fee, you can use the https://ethgasstation.info/ API to get the current gas fee or reference to [web3js](https://web3js.readthedocs.io/en/v1.2.11/web3-eth.html#getgasprice) or [ethersjs](https://docs.ethers.io/v5/api/providers/provider/#Provider-getGasPrice) `getGasPrice` function on ETH.

**Comment by zydjohnHotmail** [comment]
Thanks for your advice!
