### ISSUE TITLE
A few issues to use the repo.

### ISSUE THREAD

**Issue by zydjohnHotmail** [iamnotstatic/multichain-crypto-wallet#20]
#### Steps to reproduce the behavior

1. [First step]
2. [Second step]
3. [and so on...]

#### Logs
D:\nodejs\MultiChainCrypto>npm install multichain-crypto-wallet@0.2.7
npm WARN skipping integrity check for git dependency ssh://git@github.com/ren-forks/blake2b-wasm.git
npm WARN skipping integrity check for git dependency ssh://git@github.com/ren-forks/blake2b.git
npm WARN skipping integrity check for git dependency ssh://git@github.com/ren-forks/bitgo-utxo-lib.git
npm WARN deprecated safe-event-emitter@1.0.1: Renamed to @metamask/safe-event-emitter
npm WARN deprecated @types/web3@1.2.2: This is a stub types definition. web3 provides its own type definitions, so you do not need this installed.
npm WARN deprecated mkdirp-promise@5.0.1: This package is broken and no longer maintained. 'mkdirp' itself supports promises now, please switch to that.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated eth-sig-util@1.4.2: Deprecated in favor of '@metamask/eth-sig-util'
npm WARN deprecated ethereumjs-block@2.2.2: New package name format for new versions: @ethereumjs/block. Please update.
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated ethereumjs-tx@2.1.2: New package name format for new versions: @ethereumjs/tx. Please update.
npm WARN deprecated multicodec@1.0.4: This module has been superseded by the multiformats module
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated multibase@0.6.1: This module has been superseded by the multiformats module
npm WARN deprecated multibase@0.7.0: This module has been superseded by the multiformats module
npm WARN deprecated uuid@3.3.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated ethereumjs-tx@1.3.7: New package name format for new versions: @ethereumjs/tx. Please update.
npm WARN deprecated multicodec@0.5.7: This module has been superseded by the multiformats module
npm WARN deprecated ethereumjs-block@1.7.1: New package name format for new versions: @ethereumjs/block. Please update.
npm WARN deprecated ethereumjs-vm@2.6.0: New package name format for new versions: @ethereumjs/vm. Please update.
npm WARN deprecated axios@0.19.2: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410
npm WARN deprecated ethereumjs-common@1.5.2: New package name format for new versions: @ethereumjs/common. Please update.
npm WARN deprecated cids@0.7.5: This module has been superseded by the multiformats module

added 746 packages, and audited 747 packages in 2m

89 packages are looking for funding
  run `npm fund` for details

10 vulnerabilities (7 moderate, 3 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

#### Environment
npm version: 9.1.3
npm multichain-crypto-wallet@0.2.7
node.js: version 19.1.0
OS: Windows 10 PRO

Hello:
I have tried to use the repo to do the following.
First, install the latest version: 0.2.7, but I found a lot of deprecated packages, is it possible to update all  those deprecated packages to the latest version? So, it will look better when installing it.  Refer to the above log output for details.
I have tried to npm audit fix –force, the result was the NPM package downgraded to version 0.2.4, which was even worse, my node JavaScript not working.

The following is my first Node JavaScript to create mnemonic, it worked, but not looking good:
const wallet = require('multichain-crypto-wallet');

const mnemonic = wallet.generateMnemonic();
console.log(mnemonic);

D:\nodejs\MultiChainCrypto>node Create_Mnemonic.js
bigint: Failed to load bindings, pure JS will be used (try npm run rebuild?)
12_words_ mnemonic

The issue: bigin: Failed to load bindings, seems to be rather important, can someone fix it?

Second, as I want to create a multi-chain wallet.
I need information for the following chains:
ERC20, BEP20, HECO, TRC20 and Solana.
I can see the package contains Solana, but I can not find RPCUrl for Solana, what is Solana chain ID and network ID? and for TRC20 (Tron network) I can not find any information for Chain ID, Network ID and RPCUrl, if it is supported, let me know where can I find the necessary information.

Finally, for many tokens, like: USDT, BTC, ETH, where can I find their contract addresses, is there any list for most of the important tokens and their contract address, like for USDT, it is: 0xdac17f958d2ee523a2206206994597c13d831ec7 

Please advise,
Thanks,

**Comment by iamnotstatic** [comment]
> #### Expected behavior
> #### Actual behavior
> #### Steps to reproduce the behavior
> 1. [First step]
> 2. [Second step]
> 3. [and so on...]
> 
> #### Logs
> D:\nodejs\MultiChainCrypto>npm install multichain-crypto-wallet@0.2.7 npm WARN skipping integrity check for git dependency ssh://[git@github.com](mailto:git@github.com)/ren-forks/blake2b-wasm.git npm WARN skipping integrity check for git dependency ssh://[git@github.com](mailto:git@github.com)/ren-forks/blake2b.git npm WARN skipping integrity check for git dependency ssh://[git@github.com](mailto:git@github.com)/ren-forks/bitgo-utxo-lib.git npm WARN deprecated safe-event-emitter@1.0.1: Renamed to @metamask/safe-event-emitter npm WARN deprecated @types/web3@1.2.2: This is a stub types definition. web3 provides its own type definitions, so you do not need this installed. npm WARN deprecated mkdirp-promise@5.0.1: This package is broken and no longer maintained. 'mkdirp' itself supports promises now, please switch to that. npm WARN deprecated har-validator@5.1.5: this library is no longer supported npm WARN deprecated eth-sig-util@1.4.2: Deprecated in favor of '@metamask/eth-sig-util' npm WARN deprecated ethereumjs-block@2.2.2: New package name format for new versions: @ethereumjs/block. Please update. npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead. npm WARN deprecated ethereumjs-tx@2.1.2: New package name format for new versions: @ethereumjs/tx. Please update. npm WARN deprecated multicodec@1.0.4: This module has been superseded by the multiformats module npm WARN deprecated uuid@3.4.0: Please upgrade to version 7 or higher. Older versions may use Math.random() in certain circumstances, which is known to be problematic. See https://v8.dev/blog/math-random for details. npm WARN deprecated request@2.88.2: request has been deprecated, see [request/request#3142](https://github.com/request/request/issues/3142) npm WARN deprecated multibase@0.6.1: This module has been superseded by the multiformats module npm WARN deprecated multibase@0.7.0: This module has been superseded by the multiformats module npm WARN deprecated uuid@3.3.2: Please upgrade to version 7 or higher. Older versions may use Math.random() in certain circumstances, which is known to be problematic. See https://v8.dev/blog/math-random for details. npm WARN deprecated ethereumjs-tx@1.3.7: New package name format for new versions: @ethereumjs/tx. Please update. npm WARN deprecated multicodec@0.5.7: This module has been superseded by the multiformats module npm WARN deprecated ethereumjs-block@1.7.1: New package name format for new versions: @ethereumjs/block. Please update. npm WARN deprecated ethereumjs-vm@2.6.0: New package name format for new versions: @ethereumjs/vm. Please update. npm WARN deprecated axios@0.19.2: Critical security vulnerability fixed in v0.21.1. For more information, see [axios/axios#3410](https://github.com/axios/axios/pull/3410) npm WARN deprecated ethereumjs-common@1.5.2: New package name format for new versions: @ethereumjs/common. Please update. npm WARN deprecated cids@0.7.5: This module has been superseded by the multiformats module
> 
> added 746 packages, and audited 747 packages in 2m
> 
> 89 packages are looking for funding run `npm fund` for details
> 
> 10 vulnerabilities (7 moderate, 3 high)
> 
> To address issues that do not require attention, run: npm audit fix
> 
> To address all issues (including breaking changes), run: npm audit fix --force
> 
> Run `npm audit` for details.
> 
> #### Environment
> npm version: 9.1.3 npm multichain-crypto-wallet@0.2.7 node.js: version 19.1.0 OS: Windows 10 PRO
> 
> Hello: I have tried to use the repo to do the following. First, install the latest version: 0.2.7, but I found a lot of deprecated packages, is it possible to update all those deprecated packages to the latest version? So, it will look better when installing it. Refer to the above log output for details. I have tried to npm audit fix –force, the result was the NPM package downgraded to version 0.2.4, which was even worse, my node JavaScript not working.
> 
> The following is my first Node JavaScript to create mnemonic, it worked, but not looking good: const wallet = require('multichain-crypto-wallet');
> 
> const mnemonic = wallet.generateMnemonic(); console.log(mnemonic);
> 
> D:\nodejs\MultiChainCrypto>node Create_Mnemonic.js bigint: Failed to load bindings, pure JS will be used (try npm run rebuild?) 12_words_ mnemonic
> 
> The issue: bigin: Failed to load bindings, seems to be rather important, can someone fix it?
> 
> Second, as I want to create a multi-chain wallet. I need information for the following chains: ERC20, BEP20, HECO, TRC20 and Solana. I can see the package contains Solana, but I can not find RPCUrl for Solana, what is Solana chain ID and network ID? and for TRC20 (Tron network) I can not find any information for Chain ID, Network ID and RPCUrl, if it is supported, let me know where can I find the necessary information.
> 
> Finally, for many tokens, like: USDT, BTC, ETH, where can I find their contract addresses, is there any list for most of the important tokens and their contract address, like for USDT, it is: 0xdac17f958d2ee523a2206206994597c13d831ec7
> 
> Please advise, Thanks,

Hi, Thanks for pointing that out will look into it.

To get a chain public RPC URL, all you have to do is refer to their documentation.
Solana: https://docs.solana.com/cluster/rpc-endpoints
Binance Smart chain: https://docs.bscscan.com/misc-tools-and-utilities/public-rpc-nodes
Etheruem: https://chainlist.org/chain/1
etc.

Also, to get a token address, all you have to do is check on the chain explorer, and you search by name for the popular tokens.
![Screenshot 2022-12-03 at 13 04 35](https://user-images.githubusercontent.com/46509072/205433239-ffd202cc-bc9b-4c8d-95f5-6efc406bc173.png)
![Screenshot 2022-12-03 at 13 05 06](https://user-images.githubusercontent.com/46509072/205433254-fa6caaac-e1ca-4f82-a922-b538ec50a7dd.png)

But try to validate that you're using the actual token address.
