### ISSUE TITLE
Need list for available networks.

### ISSUE THREAD

**Issue by zydjohnHotmail** [iamnotstatic/multichain-crypto-wallet#22]
#### Steps to reproduce the behavior

1. [First step]
2. [Second step]
3. [and so on...]

#### Environment
NPM: version 9.1.3
node.js: version 19.1.0
OS: Windows 10 Pro (22H2)

Hello:
I spend some time to study the repo, but first I need some detailed information.
How many networks the repo can support.
I am interested in the following networks:
BITCOIN, ERC20, BEP20, TRC20, solana and HECO.
For example, if I want to send USDT to different network, I can write the
code like the following:

const transfer = await multichainWallet.transfer({
  recipientAddress: '0x2455eC6700092991Ce0782365A89d5Cd89c8Fa22',
  amount: 10,
  network: 'ethereum',
  rpcUrl: 'https://rpc.ankr.com/eth_goerli',
  privateKey: 'private key',
  tokenAddress: '0xdac17f958d2ee523a2206206994597c13d831ec7',
});

Let's say that, I use one address to receive USDT via ERC20 network,
but if I want to send 10 USDT to another address in BEP20 network,
which network parameter I should set?
Is it still: 'ethereum'?
Beides, I can see the rpcUrl is for testnet, not for main net, so what is
for main net for BEP20 network?
By the way, if I want to receive USDT from all 5 networks:
BITCOIN, ERC20, BEP20, TRC20, solana and HECO.
What are their network parameters:
For BITCOIN, I think it is: 'bitcoin'
For ERC20, I think it is: 'ethereum'
For BEP20, is it still: 'ethereum' or something else?
For TRC20, do you support TRON network or not yet?
For solana, I think it is: 'solana'
For HECO, is it still: 'ethereum' or something else?

Finally, there are so many tokens on 'ethereum' and on BSC network,
as long as I can get the tokens' contract address, I can receive and 
send the tokens to different network?
One example is: for token 'LEGO' (Lego-coin), its contract address is:
0x520EbCcc63E4d0804b35Cda25978BEb7159bF0CC
https://bscscan.com/token/0x520EbCcc63E4d0804b35Cda25978BEb7159bF0CC
Then I can transfer this token to and from all the supported network addresses?
Thanks for your information.

**Comment by zydjohnHotmail** [comment]
Hello:
You can't do that directly with the package, you need a bridge to be able to convert USDT ERC20 received from Ethereum to USDT BEP20 Binance Smart Chain.
Can you show me some code example for this transfer?
Thanks,

**Comment by iamnotstatic** [comment]
They're a couple of bridges you can use, like: https://cbridge.celer.network/1/56/USDT, https://exchange.chainswap.com/#/swap, https://www.bridgenetwork.com/token-bridge, etc.  You can look for their smart contract addresses  and see if you can interact with them directly using the `smartContractCall` method in the package https://github.com/iamnotstatic/multichain-crypto-wallet#ethereum-network-1

**Comment by zydjohnHotmail** [comment]
OK.
I will spend some time to read the documents.
By the way, when you can publish a new version of NPM, so it will not use a lot of legacy packages.
Thanks,

**Comment by iamnotstatic** [comment]
> OK. I will spend some time reading the documents. By the way, when you can publish a new version of NPM, so it will not use a lot of legacy packages. Thanks,

Yeah, I'm currently busy with some stuff, but once it's released, you'll receive the update.
