### ISSUE TITLE
About Restore Wallet from mnemonic keys

### ISSUE THREAD

**Issue by abbaslanbay** [iamnotstatic/multichain-crypto-wallet#24]
Hi Abdulfatai, first of all thanks for this amazing repo.
I want to asking you, How can i restore wallet from mnemonic keys? 
this should be offchain side ?

**Comment by iamnotstatic** [comment]
> Hi Abdulfatai, first of all thanks for this amazing repo. I want to asking you, How can i restore wallet from mnemonic keys? this should be offchain side ?

Yeah, it's an off-chain process all you need to pass is the derivation path

**Comment by abbaslanbay** [comment]
Hmm, I create some example but everytime will change wallet address
`  const { mnemonic } = req.body;
  const hdNode = utils.HDNode.fromMnemonic(mnemonic);
  const account = hdNode.derivePath(`m/44'/60'/0'/0/0`);
  res.status(httpStatus.OK).send({ account });`

is it normal?

**Comment by iamnotstatic** [comment]
> Hmm, I create some example but everytime will change wallet address ` const { mnemonic } = req.body; const hdNode = utils.HDNode.fromMnemonic(mnemonic); const account = hdNode.derivePath(`m/44'/60'/0'/0/0`); res.status(httpStatus.OK).send({ account });`
> 
> is it normal?

That's not the proper interaction with the package, it should be like this.

```js
multichainWallet.generateWalletFromMnemonic({
  mnemonic:
    'candy maple cake sugar pudding cream honey rich smooth crumble sweet treat',
  derivationPath: "m/44'/60'/0'/0/0",
  network: 'ethereum',
});
```

**Comment by abbaslanbay** [comment]
Got it! Thank you
