### ISSUE TITLE
Serious issues

### ISSUE THREAD

**Issue by apollo0102** [iamnotstatic/multichain-crypto-wallet#25]
After installing this package, I couldn't run my project.
Please check it
![image](https://user-images.githubusercontent.com/98648299/220952108-41597921-981f-4db1-be73-c7db770b8971.png)

**Comment by iamnotstatic** [comment]
> After installing this package, I couldn't run my project.
> Please check it
> ![image](https://user-images.githubusercontent.com/98648299/220952108-41597921-981f-4db1-be73-c7db770b8971.png)

Hi @apollo0102, 
```
Error says Module parse failed: Unexpected character * (1:0)
The module seem to be a WebAssembly module, but module is not flagged as WebAssembly module for webpack.
BREAKING CHANGE: Since webpack 5 WebAssembly is not enabled by default and flagged as experimental feature.
You need to enable one of the WebAssembly experiments via "experiments.asyndebAssembly: true" (based on async modules) or "experiments.synchebAssembly: true* (like webpack 4
For files that transpile to WebAssembly, make sure to set the module type in the "module.rules section of the config (e. g.
"type: "webassembly/async*")
(Source code omitted for this binary file)
Import trace for requested module:
/node_modules/multichain-crypto-wallet/node_modules/tiny-secp256k1/lib/secp256k1.wasm
```

Have you enabled WebAssembly ?

**Comment by apollo0102** [comment]
Hi Abdulfatai. Thanks for your email.
I'm not sure how I can enable WebAssembly. How can I enable WebAssembly?
It's a Nextjs project.
Bro
Do you have a discord or telegram account? Apollo12#4018 is my discord
account.
Can we have a chat there?  It's more comfortable for me. Please let me
know, it's not a free consultant. I'll pay you.
Sincerely
Apollo

**Comment by iamnotstatic** [comment]
> Hi Abdulfatai. Thanks for your email. I'm not sure how I can enable WebAssembly. How can I enable WebAssembly? It's a Nextjs project. Bro Do you have a discord or telegram account? Apollo12#4018 is my discord account. Can we have a chat there? It's more comfortable for me. Please let me know, it's not a free consultant. I'll pay you. Sincerely Apollo
> […](#)

You’re to add that in your `webpack.config.js`
 
 Sent you a request on discord
