### ISSUE TITLE
Hi, how to create wallet for utxo based chains like : litecoin, bitcoincash, dogecoin ?

### ISSUE THREAD

**Issue by francelwebdev** [iamnotstatic/multichain-crypto-wallet#27]
Hello, I just found this bookstore and it is really great. However, I have a question:

- how to create wallet for utxo based chains like : litecoin, bitcoincash, dogecoin ? Is it the same way to create for the bitcoin network?

THANKS

**Comment by iamnotstatic** [comment]
> Hello, I just found this bookstore and it is really great. However, I have a question:
> 
> * how to create wallet for utxo based chains like : litecoin, bitcoincash, dogecoin ? Is it the same way to create for the bitcoin network?
> 
> THANKS

Hi @francelwebdev,  Yeah Bitcoin address will also work on Bitcoin cash
