### ISSUE TITLE
TVM supported?

### ISSUE THREAD

**Issue by deantek** [iamnotstatic/multichain-crypto-wallet#28]
Hello, I want to say thank you for your work

I need to know if it is possible to add TVM support? I want to try to transfer tron ​​and trc20 tokens, if this is possible please give a small example

**Comment by iamnotstatic** [comment]
> Hello, I want to say thank you for your work
> 
> I need to know if it is possible to add TVM support? I want to try to transfer tron ​​and trc20 tokens, if this is possible please give a small example

Hi @deantek, Thanks I'm glad you found it helpful, No support for TVM atm but it's currently in works
