### ISSUE TITLE
logs?

### ISSUE THREAD

**Issue by ghost** [iamnotstatic/multichain-crypto-wallet#29]

**Comment by SamuelPaschalson** [comment]
there is no connect wallet, like after the wallet has been generated using the mnemonics

**Comment by iamnotstatic** [comment]
> Would it be good to have a decentralized log here?

Hi @stokebreakup, can you elaborate more on this, and why you need the feature ?

**Comment by SamuelPaschalson** [comment]
Ok so what i mean is that it should have a feature to connect wallet, using the mnemonics to get the wallet details, and the wallets shoulld have at least 10 coins
